#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080
sed -i '/^\s*user/c\user nginx;' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-enabled/default
sed -i 's/listen \[::\]:80/listen [::]:8080/g' /etc/nginx/sites-enabled/default
pkill -f nginx 2>/dev/null
sleep 1
nginx
