#!/usr/bin/env bash

# Update packages
apt-get update

# Install Apache if missing
apt-get install -y apache2

# Create the page
echo "Hello Holberton" > /var/www/html/index.html

echo "apache2 is running"

# Start Apache in foreground
apache2ctl -D FOREGROUND