#!/usr/bin/env bash
# shellcheck disable=SC2154

# Update & install haproxy
sudo apt-get update -y
sudo apt-get install -y haproxy

# Enable HAProxy to start on boot
sudo systemctl enable haproxy

# Backup original haproxy.cfg
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null << 'EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 03-web-01:80 check
    server web02 03-web-02:80 check
EOF

# Restart HAProxy to apply configuration
sudo systemctl restart haproxy