#!/usr/bin/env bash
# Configure nginx redirection

apt-get -y update
apt-get -y install nginx

# Add redirect inside default server block
sed -i '/server_name _;/a \
    location = /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }\n' /etc/nginx/sites-available/default

# Test configuration
nginx -t

# Restart nginx
systemctl restart nginx