#!/usr/bin/env bash
# Configure Nginx redirection /redirect_me -> YouTube

# Install nginx
apt-get -y update
apt-get -y install nginx

# Insert redirect inside server block using sed
sed -i "/listen 80 default_server;/a \
    location /redirect_me {\n\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\
    }\n" /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
