#!/usr/bin/env bash
# Configure Nginx redirection

apt-get -y update
apt-get -y install nginx

# Create nginx configuration
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location = /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Test nginx config
nginx -t

# Restart nginx
systemctl restart nginx